inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

Naming/MethodParameterName:
  Enabled: false

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Metrics/MethodLength:
  Max: 20
